// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Luna_Surveyor","status":false,"description":"An extension to the MV/MZ core that allows you to modify the in game ui\nas a UI Kit <Luna_Surveyor>.\"","parameters":{}},
{"name":"AltSaveScreen","status":false,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"SNBR_CustomMenu","status":false,"description":"Custom main menu","parameters":{"ChaptersMenuItem":"Chapters","Back":"Back","Chapters":"[]"}},
{"name":"Community_Lighting_MZ","status":true,"description":"v4.6 Creates an extra layer that darkens a map and adds lightsources! Released under the MIT license!","parameters":{"---General Settings---":"","Options Menu Entry":"Lighting Effects","Use smoother lights":"false","Light event required":"false","Triangular flashlight":"false","Shift lights with events":"false","Daynight Cycle":"true","Reset Lights":"false","Kill Switch":"None","Kill Switch Auto":"false","Note Tag Key":"cl","---DayNight Settings---":"","Daynight Initial Speed":"10","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Save Night Switch":"0","No Autoshadow During Night":"false","Night Hours":"0, 1, 2, 3, 4, 5, 6, 19, 20, 21, 22, 23","DayNight Colors":"[\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#9999ff\",\"#ccccff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffcc88\",\"#9999ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\"]","Daynight Initial Hour":"0","---Offset and Sizes---":"","Lights Active Radius":"0","Player radius":"300","Flashlight offset":"0","Flashlight X offset":"0","Screensize X":"816","Screensize Y":"624","Lightmask Padding":"32","---Battle Settings---":"","Battle Tinting":"true","Light Mask Position":"Above"}}
];
